export interface ProductSpec {
  label: string;
  value: string;
}

export interface EdgeLuxeProduct {
  modelNumber: string;
  name: string;
  family: "block-acrylic" | "fabricated-stainless" | "trimless" | "flat-cutout";
  familyLabel: string;
  slug: string;
  illumination: string;
  specs: ProductSpec[];
  heroImage: { day: string; night?: string };
}

export const products: Record<string, EdgeLuxeProduct> = {
  "LP 1": {
    modelNumber: "LP 1",
    name: "Flat Cutout Letters (FCO)",
    family: "flat-cutout",
    familyLabel: "Flat Cutout",
    slug: "non-illuminated",
    illumination: "Non-illuminated",
    heroImage: { day: "/products/flat-cut-day.jpg" },
    specs: [
      { label: "Product Line", value: "EdgeLuxe LP 1" },
      { label: "Type", value: "Flat Cutout Letters (FCO)" },
      { label: "Materials", value: "Wood, aluminum, stainless steel, acrylic" },
      { label: "Thickness", value: '1 mm (0.04") to 200 mm (7.87")' },
      { label: "Minimum Stroke Width", value: '5 mm (0.2")' },
      { label: "Minimum Height", value: '10 mm (0.4")' },
      { label: "Customization", value: "Acrylic colors, paint, vinyl" },
      { label: "Illumination", value: "None" },
      { label: "Maintenance", value: "No maintenance" },
      { label: "Lead Time", value: "3 weeks door to door" },
    ],
  },
  "LP 3.1": {
    modelNumber: "LP 3.1",
    name: "Fabricated Stainless Steel — Standoff Halo",
    family: "fabricated-stainless",
    familyLabel: "Fabricated Stainless Steel",
    slug: "stainless-standoff",
    illumination: "Halo-lit with standoff spacers",
    heroImage: {
      day: "/products/stainless-standoff-day.jpg",
      night: "/products/stainless-standoff-night.jpg",
    },
    specs: [
      { label: "Product Line", value: "EdgeLuxe LP 3.1" },
      { label: "Type", value: "Fabricated Stainless Steel — Standoff Mount" },
      { label: "Illumination", value: "Halo-lit from back with standoff spacers" },
      { label: "Depth Options", value: '30 mm (1.2"), 50 mm (2"), 80 mm (3.1"), 100 mm (3.9")' },
      { label: "Minimum Stroke Width", value: '15 mm (0.6")' },
      { label: "Minimum Height", value: '50 mm (2")' },
      { label: "Customization", value: "Any PMS color, vinyls, pigmented translucent acrylics" },
      { label: "LED Placement", value: "Arranged to avoid diode reflection on mounting surface" },
      { label: "Maintenance", value: "Serviceable LEDs" },
      { label: "Certifications", value: "UL Listed (UL 48)" },
      { label: "Lead Time", value: "3 weeks door to door" },
    ],
  },
  "LP 3.2": {
    modelNumber: "LP 3.2",
    name: "Fabricated Stainless Steel — Flush Mount",
    family: "fabricated-stainless",
    familyLabel: "Fabricated Stainless Steel",
    slug: "stainless-flush",
    illumination: "Partial side-lit flush-mounted halo",
    heroImage: {
      day: "/products/stainless-flush-day.jpg",
      night: "/products/stainless-flush-night.jpg",
    },
    specs: [
      { label: "Product Line", value: "EdgeLuxe LP 3.2" },
      { label: "Type", value: "Fabricated Stainless Steel — Flush Mount" },
      { label: "Illumination", value: "Partial side-lit flush-mounted halo effect" },
      { label: "Depth Options", value: '30 mm (1.2"), 50 mm (2"), 80 mm (3.1"), 100 mm (3.9")' },
      { label: "Minimum Stroke Width", value: '15 mm (0.6")' },
      { label: "Minimum Height", value: '50 mm (2")' },
      { label: "Customization", value: "Any PMS color, vinyls, pigmented translucent acrylics" },
      { label: "Maintenance", value: "Serviceable LEDs" },
      { label: "Certifications", value: "UL Listed (UL 48)" },
      { label: "Lead Time", value: "3 weeks door to door" },
    ],
  },
  "LP 5": {
    modelNumber: "LP 5",
    name: "Trimless Fabricated Stainless Steel",
    family: "trimless",
    familyLabel: "Trimless Stainless Steel",
    slug: "trimless",
    illumination: "Face-lit",
    heroImage: {
      day: "/products/trimless-day.jpg",
      night: "/products/trimless-night.jpg",
    },
    specs: [
      { label: "Product Line", value: "EdgeLuxe LP 5" },
      { label: "Type", value: "Trimless Fabricated Stainless Steel" },
      { label: "Construction", value: "Thick gauge SS returns + back welded, step-router acrylic face" },
      { label: "Illumination", value: "Face-lit, trim-less edge" },
      { label: "Depth Options", value: '30 mm (1.2"), 50 mm (2"), 80 mm (3.1"), 100 mm (3.9")' },
      { label: "Minimum Stroke Width", value: '15 mm (0.6")' },
      { label: "Minimum Height", value: '50 mm (2")' },
      { label: "Customization", value: "Any PMS color, vinyls, pigmented translucent acrylics" },
      { label: "Maintenance", value: "Serviceable LEDs" },
      { label: "Certifications", value: "UL Listed (UL 48)" },
      { label: "Lead Time", value: "3 weeks door to door" },
    ],
  },
  "LP 11-F": {
    modelNumber: "LP 11-F",
    name: "Block Acrylic Face-lit",
    family: "block-acrylic",
    familyLabel: "Block Acrylic",
    slug: "front-lit",
    illumination: "Face-lit",
    heroImage: {
      day: "/products/front-lit-day.jpg",
      night: "/products/front-lit-night.jpg",
    },
    specs: [
      { label: "Product Line", value: "EdgeLuxe LP 11-F" },
      { label: "Type", value: "Block Acrylic Face-lit" },
      { label: "Material", value: '30 mm (1.2") cast block acrylic' },
      { label: "Illumination", value: "Embedded LEDs for uniform face lighting" },
      { label: "Depth", value: '30 mm (1.2")' },
      { label: "Minimum Stroke Width", value: '12 mm (0.47")' },
      { label: "Minimum Height", value: '50 mm (2")' },
      { label: "Customization", value: "Any PMS color, vinyls, pigmented translucent acrylics" },
      { label: "Sealing", value: "Epoxy-sealed for IP67 waterproofing" },
      { label: "Maintenance", value: "IP67 water- and dust-proof — no maintenance" },
      { label: "Certifications", value: "UL Listed (UL 48)" },
      { label: "Lead Time", value: "3 weeks door to door" },
    ],
  },
  "LP 11-B": {
    modelNumber: "LP 11-B",
    name: "Block Acrylic Halo-lit",
    family: "block-acrylic",
    familyLabel: "Block Acrylic",
    slug: "halo-lit",
    illumination: "Halo-lit with standoff spacers",
    heroImage: {
      day: "/products/halo-lit-day.jpg",
      night: "/products/halo-lit-night.jpg",
    },
    specs: [
      { label: "Product Line", value: "EdgeLuxe LP 11-B" },
      { label: "Type", value: "Block Acrylic Back-lit (Halo)" },
      { label: "Material", value: '15 mm (0.6"), 20 mm (0.78"), or 30 mm (1.2") cast block acrylic' },
      { label: "Illumination", value: "Embedded LEDs for uniform halo-lit with standoff spacers" },
      { label: "Depth Options", value: '15 mm (0.6"), 20 mm (0.78"), 30 mm (1.2")' },
      { label: "Minimum Stroke Width", value: '12 mm (0.47")' },
      { label: "Minimum Height", value: '50 mm (2")' },
      { label: "Customization", value: "Any PMS color, vinyls, pigmented translucent acrylics" },
      { label: "Sealing", value: "Epoxy-sealed for IP67 waterproofing" },
      { label: "Maintenance", value: "IP67 water- and dust-proof — no maintenance" },
      { label: "Certifications", value: "UL Listed (UL 48)" },
      { label: "Lead Time", value: "3 weeks door to door" },
    ],
  },
  "LP 11-FB": {
    modelNumber: "LP 11-FB",
    name: "Block Acrylic Face & Halo-lit",
    family: "block-acrylic",
    familyLabel: "Block Acrylic",
    slug: "front-and-halo-lit",
    illumination: "Face-lit and halo-lit with standoff spacers",
    heroImage: {
      day: "/products/front-halo-day.jpg",
      night: "/products/front-halo-night.jpg",
    },
    specs: [
      { label: "Product Line", value: "EdgeLuxe LP 11-FB" },
      { label: "Type", value: "Block Acrylic Face- and Halo-lit Combo" },
      { label: "Material", value: '30 mm (1.2") cast block acrylic' },
      { label: "Illumination", value: "Embedded LEDs for uniform face- and halo-lit with standoff spacers" },
      { label: "Depth", value: '30 mm (1.2")' },
      { label: "Minimum Stroke Width", value: '12 mm (0.47")' },
      { label: "Minimum Height", value: '50 mm (2")' },
      { label: "Customization", value: "Any PMS color, vinyls, pigmented translucent acrylics" },
      { label: "Sealing", value: "Epoxy-sealed for IP67 waterproofing" },
      { label: "Maintenance", value: "IP67 water- and dust-proof — no maintenance" },
      { label: "Certifications", value: "UL Listed (UL 48)" },
      { label: "Lead Time", value: "3 weeks door to door" },
    ],
  },
  "LP 11-BS": {
    modelNumber: "LP 11-BS",
    name: "Block Acrylic Partial Back Side-lit",
    family: "block-acrylic",
    familyLabel: "Block Acrylic",
    slug: "back-side-lit",
    illumination: "Partial back side-lit, flush-mount",
    heroImage: {
      day: "/products/back-side-day.jpg",
      night: "/products/back-side-night.jpg",
    },
    specs: [
      { label: "Product Line", value: "EdgeLuxe LP 11-BS" },
      { label: "Type", value: "Block Acrylic Partial Back Side-lit" },
      { label: "Material", value: '30 mm (1.2") cast block acrylic' },
      { label: "Illumination", value: "Embedded LEDs for uniform partial back side-lit, flush-mount" },
      { label: "Depth", value: '30 mm (1.2")' },
      { label: "Minimum Stroke Width", value: '12 mm (0.47")' },
      { label: "Minimum Height", value: '50 mm (2")' },
      { label: "Customization", value: "Any PMS color, vinyls, pigmented translucent acrylics" },
      { label: "Sealing", value: "Epoxy-sealed for IP67 waterproofing" },
      { label: "Maintenance", value: "IP67 water- and dust-proof — no maintenance" },
      { label: "Certifications", value: "UL Listed (UL 48)" },
      { label: "Lead Time", value: "3 weeks door to door" },
    ],
  },
  "LP 11-FS": {
    modelNumber: "LP 11-FS",
    name: "Block Acrylic Partial Front Side-lit",
    family: "block-acrylic",
    familyLabel: "Block Acrylic",
    slug: "front-side-lit",
    illumination: "Partial front side-lit, flush-mount",
    heroImage: {
      day: "/products/face-side-day.jpg",
      night: "/products/face-side-night.jpg",
    },
    specs: [
      { label: "Product Line", value: "EdgeLuxe LP 11-FS" },
      { label: "Type", value: "Block Acrylic Partial Front Side-lit" },
      { label: "Material", value: '30 mm (1.2") cast block acrylic' },
      { label: "Illumination", value: "Embedded LEDs for uniform partial front side-lit, flush-mount" },
      { label: "Depth", value: '30 mm (1.2")' },
      { label: "Minimum Stroke Width", value: '12 mm (0.47")' },
      { label: "Minimum Height", value: '50 mm (2")' },
      { label: "Customization", value: "Any PMS color, vinyls, pigmented translucent acrylics" },
      { label: "Sealing", value: "Epoxy-sealed for IP67 waterproofing" },
      { label: "Maintenance", value: "IP67 water- and dust-proof — no maintenance" },
      { label: "Certifications", value: "UL Listed (UL 48)" },
      { label: "Lead Time", value: "3 weeks door to door" },
    ],
  },
  "LP 11-S": {
    modelNumber: "LP 11-S",
    name: "Block Acrylic Full Side-lit",
    family: "block-acrylic",
    familyLabel: "Block Acrylic",
    slug: "side-lit",
    illumination: "Full side-lit",
    heroImage: {
      day: "/products/side-lit-day.jpg",
      night: "/products/side-lit-night.jpg",
    },
    specs: [
      { label: "Product Line", value: "EdgeLuxe LP 11-S" },
      { label: "Type", value: "Block Acrylic Full Side-lit" },
      { label: "Material", value: '30 mm (1.2") cast block acrylic' },
      { label: "Illumination", value: "Embedded LEDs for uniform full side-lit" },
      { label: "Depth", value: '30 mm (1.2")' },
      { label: "Minimum Stroke Width", value: '12 mm (0.47")' },
      { label: "Minimum Height", value: '50 mm (2")' },
      { label: "Customization", value: "Any PMS color, vinyls, pigmented translucent acrylics" },
      { label: "Sealing", value: "Epoxy-sealed for IP67 waterproofing" },
      { label: "Maintenance", value: "IP67 water- and dust-proof — no maintenance" },
      { label: "Certifications", value: "UL Listed (UL 48)" },
      { label: "Lead Time", value: "3 weeks door to door" },
    ],
  },
  "LP 11-N": {
    modelNumber: "LP 11-N",
    name: "Block Acrylic Faux Neon",
    family: "block-acrylic",
    familyLabel: "Block Acrylic",
    slug: "faux-neon",
    illumination: "Face-lit, routed to simulate neon glass tube",
    heroImage: {
      day: "/products/faux-neon-day.jpg",
      night: "/products/faux-neon-night.jpg",
    },
    specs: [
      { label: "Product Line", value: "EdgeLuxe LP 11-N" },
      { label: "Type", value: "Block Acrylic Faux Neon" },
      { label: "Material", value: '30 mm (1.2") cast block acrylic' },
      { label: "Illumination", value: "Embedded LEDs, routed to simulate neon glass tube" },
      { label: "Depth", value: '30 mm (1.2")' },
      { label: "Minimum Stroke Width", value: '12 mm (0.47")' },
      { label: "Minimum Height", value: '50 mm (2")' },
      { label: "Customization", value: "Any PMS color, vinyls, pigmented translucent acrylics" },
      { label: "Sealing", value: "Epoxy-sealed for IP67 waterproofing" },
      { label: "Maintenance", value: "IP67 water- and dust-proof — no maintenance" },
      { label: "Certifications", value: "UL Listed (UL 48)" },
      { label: "Lead Time", value: "3 weeks door to door" },
    ],
  },
  "LP 11-C": {
    modelNumber: "LP 11-C",
    name: "Block Acrylic Conical Profile",
    family: "block-acrylic",
    familyLabel: "Block Acrylic",
    slug: "conical",
    illumination: "Face-lit, conical profile for narrow strokes and serifs",
    heroImage: {
      day: "/products/conical-day.jpg",
      night: "/products/conical-night.jpg",
    },
    specs: [
      { label: "Product Line", value: "EdgeLuxe LP 11-C" },
      { label: "Type", value: "Block Acrylic Conical Profile" },
      { label: "Material", value: '30 mm (1.2") cast block acrylic' },
      { label: "Illumination", value: "Embedded LEDs, conical profile for narrow strokes and serifs" },
      { label: "Depth", value: '30 mm (1.2")' },
      { label: "Minimum Stroke Width", value: '12 mm (0.47") back, down to 3 mm (0.12") on face' },
      { label: "Minimum Height", value: '50 mm (2")' },
      { label: "Customization", value: "Any PMS color, vinyls, pigmented translucent acrylics" },
      { label: "Sealing", value: "Epoxy-sealed for IP67 waterproofing" },
      { label: "Maintenance", value: "IP67 water- and dust-proof — no maintenance" },
      { label: "Certifications", value: "UL Listed (UL 48)" },
      { label: "Lead Time", value: "3 weeks door to door" },
    ],
  },
};

export function getProduct(modelNumber: string): EdgeLuxeProduct {
  const product = products[modelNumber];
  if (!product) throw new Error(`Product not found: ${modelNumber}`);
  return product;
}

export function getProductsByFamily(family: EdgeLuxeProduct["family"]): EdgeLuxeProduct[] {
  return Object.values(products).filter((p) => p.family === family);
}
